const R_UNCONNECTED = 0;
const R_DASHBOARD = 1;
const R_CAMPAIGNS = 2;
const R_REWARDS = 3;
const R_LOANS = 4;
const R_DEPOSIT = 5;

export {R_UNCONNECTED, R_DASHBOARD, R_CAMPAIGNS, R_REWARDS, R_LOANS, R_DEPOSIT}